function getLems(x) {
    x = x.toLowerCase();
    var rs = [];
    if (lemExs2.has(x)) {
        rs.push(x);
        return rs;
    }
    
    rs.push(x);
    var l = lemExs.get(x);
    if (l) {
        rs.push(l);
        return rs;
    }
    
    var esRe = /(ss|zz|x|sh|ch|o|i)es$/;
    var sRe = /([^yuoaies]|[^yuoaie]e)s$/;
    var ingEdRe = /(ing|ed)$/;
    var woutIngEd = x.replace(ingEdRe, "");
    if (x.endsWith("s")) {
        if (esRe.test(x)) {
            x = x.replace(esRe, "$1");
            x = x.replace(/i$/, "y");
            rs.push(x);
        }
        else if (sRe.test(x)) {
            x = x.replace(sRe, "$1");
            rs.push(x);
        }
    }
    else if (ingEdRe.test(x) && /[yuoaie]/.test(woutIngEd)) {
        x = woutIngEd;
        if (/(bb|dd|ff|gg|mm|nn|pp|rr|tt)$/.test(x)) {
            x = x.substr(0, x.length - 1);
            rs.push(x);
        }
        else {
            rs.push(x);
            rs.push(x + "e");
        }
    }
    else if (x.endsWith("est")) {
        x = x.replace(/est$/, "");
        x = x.replace(/i$/, "y");
        if (/(bb|dd|ff|gg|mm|nn|pp|rr|tt)$/.test(x)) {
            x = x.replace(/.$/, "");
        }
        else if (/[^yuoaie]$/.test(x)) {
            rs.push(x + "e");
        }
        rs.push(x);
    }
    else {
        rs.push(x);
    }
    
    return rs;
}

var lemExs = new Map([
["an", "a"],
["abode", "abide"],
["abler", "able"],
["absentees", "absentee"],
["accompanied", "accompany"],
["accrues", "accrue"],
["aches", "ache"],
["adding", "add"],
["added", "add"],
["agendas", "agenda"],
["agrees", "agree"],
["airmen", "airman"],
["airways", "airway"],
["airier", "airy"],
["aldermen", "alderman"],
["alibis", "alibi"],
["alit", "alight"],
["allays", "allay"],
["alleys", "alley"],
["alleyways", "alleyway"],
["alloys", "alloy"],
["allied", "ally"],
["alphas", "alpha"],
["alumni", "alumnus"],
["amplified", "amplify"],
["analyses", "analysis"],
["analytical", "analytic"],
["angrier", "angry"],
["annoys", "annoy"],
["antennae", "antenna"],
["antennas", "antenna"],
["antiques", "antique"],
["antitheses", "antithesis"],
["appalling", "appal"],
["appalled", "appal"],
["apparatuses", "apparatus"],
["appendices", "appendix"],
["applied", "apply"],
["appointees", "appointee"],
["aquaria", "aquarium"],
["archipelagos", "archipelago"],
["archways", "archway"],
["areas", "area"],
["arenas", "arena"],
["argues", "argue"],
["arias", "aria"],
["arose", "arise"],
["arisen", "arise"],
["aromas", "aroma"],
["arrays", "array"],
["ashtrays", "ashtray"],
["assays", "assay"],
["atlases", "atlas"],
["attorneys", "attorney"],
["auditoria", "auditorium"],
["auras", "aura"],
["autos", "auto"],
["avalanches", "avalanche"],
["avenues", "avenue"],
["avocados", "avocado"],
["awoke", "awake"],
["awoken", "awake"],
["axes", "axe"],
["axes", "axis"],
["ayes", "aye"],
["baby-sat", "baby-sit"],
["worse", "bad"],
["worst", "bad"],
["baggier", "baggy"],
["balder", "bald"],
["ballerinas", "ballerina"],
["balmier", "balmy"],
["bamboos", "bamboo"],
["bananas", "banana"],
["bandannas", "bandanna"],
["banjos", "banjo"],
["barbecues", "barbecue"],
["barer", "bare"],
["baser", "base"],
["bases", "basis"],
["bays", "bay"],
["am", "be"],
["are", "be"],
["is", "be"],
["was", "be"],
["were", "be"],
["been", "be"],
["'m", "be"],
["m", "be"],
["bore", "bear"],
["borne", "bear"],
["beaten", "beat"],
["beaux", "beau"],
["beaus", "beau"],
["became", "become"],
["bees", "bee"],
["beefier", "beefy"],
["befell", "befall"],
["befallen", "befall"],
["began", "begin"],
["begun", "begin"],
["beheld", "behold"],
["belies", "belie"],
["belying", "belie"],
["bellied", "belly"],
["bent", "bend"],
["bereft", "bereave"],
["betas", "beta"],
["betrays", "betray"],
["biases", "bias"],
["bode", "bide"],
["bigger", "big"],
["bikinis", "bikini"],
["bound", "bind"],
["birdies", "birdie"],
["birthdays", "birthday"],
["bistros", "bistro"],
["bit", "bite"],
["bitten", "bite"],
["blacker", "black"],
["blander", "bland"],
["blanker", "blank"],
["bleaker", "bleak"],
["bled", "bleed"],
["blent", "blend"],
["blitzes", "blitz"],
["bloodied", "bloody"],
["bloodier", "bloody"],
["blew", "blow"],
["blown", "blow"],
["bluer", "blue"],
["blues", "blue"],
["bluffing", "bluff"],
["bluffed", "bluff"],
["blunter", "blunt"],
["blurrier", "blurry"],
["bogeys", "bogey"],
["bolder", "bold"],
["bonanzas", "bonanza"],
["bonuses", "bonus"],
["bonier", "bony"],
["boos", "boo"],
["bookshelves", "bookshelf"],
["boutiques", "boutique"],
["boys", "boy"],
["boycotting", "boycott"],
["boycotted", "boycott"],
["bras", "bra"],
["brasher", "brash"],
["braver", "brave"],
["broke", "break"],
["broken", "break"],
["breast-fed", "breast-feed"],
["bred", "breed"],
["breezier", "breezy"],
["briefer", "brief"],
["brighter", "bright"],
["brought", "bring"],
["brisker", "brisk"],
["brittler", "brittle"],
["broader", "broad"],
["brethren", "brother"],
["brothers-in-law", "brother-in-law"],
["browner", "brown"],
["brownies", "brownie"],
["bubblier", "bubbly"],
["buffing", "buff"],
["buffed", "buff"],
["built", "build"],
["bulkier", "bulky"],
["bullied", "bully"],
["bumpier", "bumpy"],
["buoys", "buoy"],
["bureaux", "bureau"],
["bureaus", "bureau"],
["burlier", "burly"],
["burnt", "burn"],
["burned-out", "burnt-out"],
["buried", "bury"],
["buses", "bus"],
["busses", "bus"],
["bussing", "bus"],
["bussed", "bus"],
["bushier", "bushy"],
["businessmen", "businessman"],
["busier", "busy"],
["busied", "busy"],
["butting", "butt"],
["butted", "butt"],
["buys", "buy"],
["bought", "buy"],
["caches", "cache"],
["cactuses", "cactus"],
["cacti", "cactus"],
["caddies", "caddie"],
["caddying", "caddie"],
["cafeterias", "cafeteria"],
["calves", "calf"],
["calmer", "calm"],
["cameos", "cameo"],
["cameras", "camera"],
["cameramen", "cameraman"],
["campuses", "campus"],
["cancelling", "cancel"],
["cancelled", "cancel"],
["canoes", "canoe"],
["canvases", "canvas"],
["caribous", "caribou"],
["carolling", "carol"],
["carolled", "carol"],
["carried", "carry"],
["casinos", "casino"],
["catalogues", "catalogue"],
["caught", "catch"],
["catchier", "catchy"],
["caucuses", "caucus"],
["cellos", "cello"],
["censuses", "census"],
["certified", "certify"],
["chairmen", "chairman"],
["chairwomen", "chairwoman"],
["channelling", "channel"],
["channelled", "channel"],
["cheaper", "cheap"],
["cheerier", "cheery"],
["chewier", "chewy"],
["chickpeas", "chickpea"],
["chid", "chide"],
["children", "child"],
["chillier", "chilly"],
["chimneys", "chimney"],
["chimpanzees", "chimpanzee"],
["chiselling", "chisel"],
["chiselled", "chisel"],
["choicer", "choice"],
["chose", "choose"],
["chosen", "choose"],
["choppier", "choppy"],
["choruses", "chorus"],
["christmases", "christmas"],
["chubbier", "chubby"],
["chunkier", "chunky"],
["chutneys", "chutney"],
["cicadas", "cicada"],
["cinemas", "cinema"],
["circuses", "circus"],
["clarified", "clarify"],
["classified", "classify"],
["classier", "classy"],
["cleaner", "clean"],
["clearer", "clear"],
["clove", "cleave"],
["cleft", "cleave"],
["cloven", "cleave"],
["clergymen", "clergyman"],
["cleverer", "clever"],
["cliches", "cliche"],
["clung", "cling"],
["cliques", "clique"],
["closer", "close"],
["clad", "clothe"],
["clues", "clue"],
["clumsier", "clumsy"],
["coarser", "coarse"],
["cockier", "cocky"],
["codified", "codify"],
["coffees", "coffee"],
["colas", "cola"],
["colder", "cold"],
["colleagues", "colleague"],
["collies", "collie"],
["comas", "coma"],
["combos", "combo"],
["came", "come"],
["comfier", "comfy"],
["commas", "comma"],
["commanders-in-chief", "commander-in-chief"],
["commandos", "commando"],
["committees", "committee"],
["commoner", "common"],
["communiques", "communique"],
["compelling", "compel"],
["compelled", "compel"],
["complied", "comply"],
["concertos", "concerto"],
["congressmen", "congressman"],
["consortia", "consortium"],
["construes", "construe"],
["continues", "continue"],
["controlling", "control"],
["controlled", "control"],
["conveys", "convey"],
["convoys", "convoy"],
["coos", "coo"],
["cookies", "cookie"],
["cooler", "cool"],
["copied", "copy"],
["corduroys", "corduroy"],
["cornier", "corny"],
["coronas", "corona"],
["corpora", "corpus"],
["corpuses", "corpus"],
["corralling", "corral"],
["corralled", "corral"],
["cortices", "cortex"],
["costlier", "costly"],
["counselling", "counsel"],
["counselled", "counsel"],
["countrymen", "countryman"],
["courtlier", "courtly"],
["cowboys", "cowboy"],
["craftsmen", "craftsman"],
["craftier", "crafty"],
["crankier", "cranky"],
["crasser", "crass"],
["crazier", "crazy"],
["creamier", "creamy"],
["credos", "credo"],
["crept", "creep"],
["creepier", "creepy"],
["crescendos", "crescendo"],
["crescendi", "crescendo"],
["crewmen", "crewman"],
["crises", "crisis"],
["crisper", "crisp"],
["crispier", "crispy"],
["criteria", "criterion"],
["critiques", "critique"],
["crosser", "cross"],
["crew", "crow"],
["crucified", "crucify"],
["cruder", "crude"],
["crueller", "cruel"],
["crunchier", "crunchy"],
["crustier", "crusty"],
["cried", "cry"],
["cues", "cue"],
["cuffing", "cuff"],
["cuffed", "cuff"],
["curlier", "curly"],
["curricula", "curriculum"],
["curried", "curry"],
["curst", "curse"],
["cuter", "cute"],
["daintier", "dainty"],
["damper", "damp"],
["dandier", "dandy"],
["danker", "dank"],
["darker", "dark"],
["daughters-in-law", "daughter-in-law"],
["days", "day"],
["deadlier", "deadly"],
["deafer", "deaf"],
["dealt", "deal"],
["dearer", "dear"],
["decays", "decay"],
["decoys", "decoy"],
["decrees", "decree"],
["decried", "decry"],
["deeper", "deep"],
["defter", "deft"],
["defied", "defy"],
["degrees", "degree"],
["delays", "delay"],
["deltas", "delta"],
["demos", "demo"],
["denser", "dense"],
["denied", "deny"],
["deploys", "deploy"],
["destroys", "destroy"],
["detainees", "detainee"],
["devalues", "devalue"],
["devotees", "devotee"],
["diagnoses", "diagnosis"],
["dialling", "dial"],
["dialled", "dial"],
["dialogues", "dialogue"],
["dicta", "dictum"],
["dies", "die"],
["dying", "die"],
["dug", "dig"],
["dignified", "dignify"],
["dilemmas", "dilemma"],
["dimmer", "dim"],
["dingier", "dingy"],
["diplomas", "diploma"],
["dirtier", "dirty"],
["dirtied", "dirty"],
["disagrees", "disagree"],
["discos", "disco"],
["discontinues", "discontinue"],
["dismays", "dismay"],
["disobeys", "disobey"],
["dispelling", "dispel"],
["dispelled", "dispel"],
["displays", "display"],
["disqualified", "disqualify"],
["distilling", "distil"],
["distilled", "distil"],
["dove", "dive"],
["diversified", "diversify"],
["dizzier", "dizzy"],
["dizzied", "dizzy"],
["did", "do"],
["done", "do"],
["does", "doe"],
["dogmas", "dogma"],
["donkeys", "donkey"],
["doormen", "doorman"],
["doorways", "doorway"],
["drabber", "drab"],
["dramas", "drama"],
["drew", "draw"],
["drawn", "draw"],
["dreamt", "dream"],
["dreamier", "dreamy"],
["drearier", "dreary"],
["drank", "drink"],
["drunk", "drink"],
["dript", "drip"],
["drove", "drive"],
["driven", "drive"],
["driveways", "driveway"],
["drowsier", "drowsy"],
["drier", "dry"],
["dryer", "dry"],
["dues", "due"],
["duelling", "duel"],
["duelled", "duel"],
["duller", "dull"],
["dumber", "dumb"],
["duos", "duo"],
["duskier", "dusky"],
["dustier", "dusty"],
["dwelt", "dwell"],
["dyes", "dye"],
["earlier", "early"],
["easier", "easy"],
["ate", "eat"],
["eaten", "eat"],
["ebbing", "ebb"],
["ebbed", "ebb"],
["eddied", "eddy"],
["edgier", "edgy"],
["eerier", "eerie"],
["egging", "egg"],
["egged", "egg"],
["egos", "ego"],
["electrified", "electrify"],
["elves", "elf"],
["embodied", "embody"],
["embryos", "embryo"],
["emphases", "emphasis"],
["employs", "employ"],
["employees", "employee"],
["emptier", "empty"],
["emptied", "empty"],
["enamelling", "enamel"],
["enamelled", "enamel"],
["encompass", "encompass"],
["encyclopedias", "encyclopedia"],
["englishmen", "englishman"],
["enigmas", "enigma"],
["enjoys", "enjoy"],
["ensues", "ensue"],
["entrees", "entree"],
["envoys", "envoy"],
["envied", "envy"],
["equalling", "equal"],
["equalled", "equal"],
["equilibria", "equilibrium"],
["eras", "era"],
["erring", "err"],
["erred", "err"],
["espressos", "espresso"],
["essays", "essay"],
["evacuees", "evacuee"],
["excelling", "excel"],
["excelled", "excel"],
["exemplified", "exemplify"],
["expelling", "expel"],
["expelled", "expel"],
["extolling", "extol"],
["extolled", "extol"],
["extras", "extra"],
["extravaganzas", "extravaganza"],
["eyes", "eye"],
["fainter", "faint"],
["fairer", "fair"],
["fairways", "fairway"],
["fell", "fall"],
["fallen", "fall"],
["falser", "false"],
["falsified", "falsify"],
["fancied", "fancy"],
["fancier", "fancy"],
["farther", "far"],
["faster", "fast"],
["fatter", "fat"],
["fathers-in-law", "father-in-law"],
["fatigues", "fatigue"],
["fattier", "fatty"],
["fees", "fee"],
["feebler", "feeble"],
["fed", "feed"],
["felt", "feel"],
["femora", "femur"],
["ferried", "ferry"],
["fewer", "few"],
["fiancees", "fiancee"],
["fiascos", "fiasco"],
["fiercer", "fierce"],
["fierier", "fiery"],
["fiestas", "fiesta"],
["fought", "fight"],
["filipinos", "filipino"],
["filthier", "filthy"],
["found", "find"],
["finer", "fine"],
["firemen", "fireman"],
["firmer", "firm"],
["fishermen", "fisherman"],
["fishier", "fishy"],
["fitter", "fit"],
["flannelling", "flannel"],
["flannelled", "flannel"],
["flashier", "flashy"],
["flatter", "flat"],
["fleas", "flea"],
["flees", "flee"],
["fled", "flee"],
["fleshier", "fleshy"],
["flimsier", "flimsy"],
["flung", "fling"],
["floppier", "floppy"],
["fluffing", "fluff"],
["fluffed", "fluff"],
["fluffier", "fluffy"],
["flew", "fly"],
["flied", "fly"],
["flown", "fly"],
["foci", "focus"],
["focuses", "focus"],
["foes", "foe"],
["foggier", "foggy"],
["fonder", "fond"],
["feet", "foot"],
["forays", "foray"],
["forbade", "forbid"],
["forbidden", "forbid"],
["forewent", "forego"],
["foregone", "forego"],
["foremen", "foreman"],
["foresees", "foresee"],
["foresaw", "foresee"],
["foreseen", "foresee"],
["forgot", "forget"],
["forgotten", "forget"],
["forgave", "forgive"],
["forgiven", "forgive"],
["forwent", "forgo"],
["forgone", "forgo"],
["formulae", "formula"],
["formulas", "formula"],
["forsook", "forsake"],
["forsaken", "forsake"],
["fortified", "fortify"],
["fouler", "foul"],
["frailer", "frail"],
["franker", "frank"],
["frays", "fray"],
["frees", "free"],
["freer", "free"],
["freemen", "freeman"],
["freeways", "freeway"],
["froze", "freeze"],
["frozen", "freeze"],
["frenchmen", "frenchman"],
["fresher", "fresh"],
["freshmen", "freshman"],
["friendlier", "friendly"],
["frostier", "frosty"],
["frothier", "frothy"],
["fruitier", "fruity"],
["fried", "fry"],
["fuelling", "fuel"],
["fuelled", "fuel"],
["fulfilling", "fulfil"],
["fulfilled", "fulfil"],
["fuller", "full"],
["fungi", "fungus"],
["funguses", "fungus"],
["funkier", "funky"],
["funnelling", "funnel"],
["funnelled", "funnel"],
["funnier", "funny"],
["furrier", "furry"],
[" furtherst", "further"],
["fussier", "fussy"],
["fuzzier", "fuzzy"],
["galas", "gala"],
["galleys", "galley"],
["gammas", "gamma"],
["gases", "gas"],
["gasses", "gas"],
["gassing", "gas"],
["gassed", "gas"],
["gateways", "gateway"],
["gaudier", "gaudy"],
["gays", "gay"],
["gayer", "gay"],
["gelling", "gel"],
["gelled", "gel"],
["genies", "genie"],
["geniuses", "genius"],
["gentler", "gentle"],
["gentlemen", "gentleman"],
["genera", "genus"],
["got", "get"],
["gotten", "get"],
["getaways", "getaway"],
["ghettos", "ghetto"],
["gis", "gi"],
["giddier", "giddy"],
["gilt", "gild"],
["gave", "give"],
["given", "give"],
["gladder", "glad"],
["glibber", "glib"],
["gloomier", "gloomy"],
["glorified", "glorify"],
["gloried", "glory"],
["glues", "glue"],
["went", "go"],
["gone", "go"],
["goalies", "goalie"],
["goatees", "goatee"],
["gondolas", "gondola"],
["better-looking", "good-looking"],
["best-looking", "good-looking"],
["goodbyes", "goodbye"],
["gooier", "gooey"],
["goofier", "goofy"],
["geese", "goose"],
["gorillas", "gorilla"],
["gorier", "gory"],
["grander", "grand"],
["grandchildren", "grandchild"],
["grandmas", "grandma"],
["grandpas", "grandpa"],
["grassier", "grassy"],
["gratified", "gratify"],
["graven", "grave"],
["greasier", "greasy"],
["greater", "great"],
["greedier", "greedy"],
["greener", "green"],
["grimmer", "grim"],
["ground", "grind"],
["grittier", "gritty"],
["groggier", "groggy"],
["grosser", "gross"],
["grottos", "grotto"],
["groupies", "groupie"],
["grew", "grow"],
["grown", "grow"],
["grumpier", "grumpy"],
["guarantees", "guarantee"],
["guerrillas", "guerrilla"],
["guiltier", "guilty"],
["guineas", "guinea"],
["gunmen", "gunman"],
["gurus", "guru"],
["guys", "guy"],
["hairdos", "hairdo"],
["hairier", "hairy"],
["halves", "half"],
["hallways", "hallway"],
["halos", "halo"],
["hamstrung", "hamstring"],
["handcuffing", "handcuff"],
["handcuffed", "handcuff"],
["handier", "handy"],
["hung", "hang"],
["happier", "happy"],
["harder", "hard"],
["hardier", "hardy"],
["harmonicas", "harmonica"],
["harsher", "harsh"],
["hastier", "hasty"],
["has", "have"],
["had", "have"],
["'d", "have"],
["'ve", "have"],
["d", "have"],
["ve", "have"],
["hazier", "hazy"],
["headaches", "headache"],
["headier", "heady"],
["healthier", "healthy"],
["heard", "hear"],
["heartaches", "heartache"],
["heartier", "hearty"],
["hove", "heave"],
["heavier", "heavy"],
["heftier", "hefty"],
["hellos", "hello"],
["hewn", "hew"],
["hiatuses", "hiatus"],
["hid", "hide"],
["hidden", "hide"],
["hideaways", "hideaway"],
["higher", "high"],
["highways", "highway"],
["hillier", "hilly"],
["hindus", "hindu"],
["hippies", "hippie"],
["hoarser", "hoarse"],
["hoes", "hoe"],
["held", "hold"],
["holidays", "holiday"],
["holier", "holy"],
["honeys", "honey"],
["hornier", "horny"],
["horrified", "horrify"],
["horsemen", "horseman"],
["horseshoes", "horseshoe"],
["hotter", "hot"],
["housewives", "housewife"],
["hues", "hue"],
["huffing", "huff"],
["huffed", "huff"],
["huger", "huge"],
["humbler", "humble"],
["hungrier", "hungry"],
["hurried", "hurry"],
["huskier", "husky"],
["hyenas", "hyena"],
["hypotheses", "hypothesis"],
["icier", "icy"],
["ideas", "idea"],
["identified", "identify"],
["imbues", "imbue"],
["impelling", "impel"],
["impelled", "impel"],
["imperilling", "imperil"],
["imperilled", "imperil"],
["implied", "imply"],
["incursion", "incursion"],
["indices", "index"],
["infernos", "inferno"],
["initialling", "initial"],
["initialled", "initial"],
["inlays", "inlay"],
["inlaid", "inlay"],
["instilling", "instil"],
["instilled", "instil"],
["intensified", "intensify"],
["interviewees", "interviewee"],
["interwove", "interweave"],
["interwoven", "interweave"],
["intrigues", "intrigue"],
["iraqis", "iraqi"],
["irises", "iris"],
["irishmen", "irishman"],
["israelis", "israeli"],
["issues", "issue"],
["jerkier", "jerky"],
["jerseys", "jersey"],
["jigsawn", "jigsaw"],
["jockeys", "jockey"],
["jollier", "jolly"],
["journeys", "journey"],
["joys", "joy"],
["juicier", "juicy"],
["jumbos", "jumbo"],
["junkies", "junkie"],
["juntas", "junta"],
["justified", "justify"],
["kangaroos", "kangaroo"],
["keener", "keen"],
["kept", "keep"],
["keys", "key"],
["kidneys", "kidney"],
["kimonos", "kimono"],
["kinder", "kind"],
["knees", "knee"],
["knelt", "kneel"],
["knives", "knife"],
["knew", "know"],
["known", "know"],
["kuwaitis", "kuwaiti"],
["labelling", "label"],
["labelled", "label"],
["lacier", "lacy"],
["laden", "lade"],
["lamer", "lame"],
["lankier", "lanky"],
["larger", "large"],
["larvae", "larva"],
["later", "late"],
["laxer", "lax"],
["laymen", "layman"],
["lazier", "lazy"],
["led", "lead"],
["leaves", "leaf"],
["leagues", "league"],
["leakier", "leaky"],
["leant", "lean"],
["leant", "lean"],
["leapt", "leap"],
["learnt", "learn"],
["left", "leave"],
["lent", "lend"],
["lengthier", "lengthy"],
["lenses", "lens"],
["levelling", "level"],
["levelled", "level"],
["levied", "levy"],
["libelling", "libel"],
["libelled", "libel"],
["libidos", "libido"],
["lies", "lie"],
["lying", "lie"],
["lay", "lie"],
["lain", "lie"],
["lives", "life"],
["lit", "light"],
["likelier", "likely"],
["limper", "limp"],
["livelier", "lively"],
["llamas", "llama"],
["loaves", "loaf"],
["lobbied", "lobby"],
["loci", "locus"],
["loftier", "lofty"],
["logos", "logo"],
["lonelier", "lonely"],
["longer", "long"],
["longer-lasting", "long-lasting"],
["longest-running", "long-running"],
["longer-term", "long-term"],
["looser", "loose"],
["lost", "lose"],
["louder", "loud"],
["lice", "louse"],
["lousier", "lousy"],
["lovelier", "lovely"],
["lower", "low"],
["lowlier", "lowly"],
["luckier", "lucky"],
["lumpier", "lumpy"],
["lusher", "lush"],
["madder", "mad"],
["madmen", "madman"],
["maestros", "maestro"],
["magicking", "magic"],
["magicked", "magic"],
["magnified", "magnify"],
["magnolias", "magnolia"],
["mailmen", "mailman"],
["mainstays", "mainstay"],
["made", "make"],
["mamas", "mama"],
["men", "man"],
["mangos", "mango"],
["manias", "mania"],
["manifestos", "manifesto"],
["manlier", "manly"],
["marinas", "marina"],
["marquees", "marquee"],
["married", "marry"],
["marshalling", "marshal"],
["marshalled", "marshal"],
["marvelling", "marvel"],
["marvelled", "marvel"],
["matinees", "matinee"],
["matrices", "matrix"],
["maturer", "mature"],
["meant", "mean"],
["meatier", "meaty"],
["meccas", "mecca"],
["media", "medium"],
["medleys", "medley"],
["meeker", "meek"],
["met", "meet"],
["melees", "melee"],
["mellower", "mellow"],
["melodramas", "melodrama"],
["molten", "melt"],
["mementos", "memento"],
["memos", "memo"],
["memoranda", "memorandum"],
["menus", "menu"],
["meringues", "meringue"],
["merrier", "merry"],
["messier", "messy"],
["metamorphoses", "metamorphosis"],
["metros", "metro"],
["metropolises", "metropolis"],
["micros", "micro"],
["midwives", "midwife"],
["mightier", "mighty"],
["milder", "mild"],
["milieux", "milieu"],
["milieus", "milieu"],
["militias", "militia"],
["militiamen", "militiaman"],
["milkier", "milky"],
["millennia", "millennium"],
["mimicking", "mimic"],
["mimicked", "mimic"],
["minis", "mini"],
["minusses", "minus"],
["minuses", "minus"],
["misled", "mislead"],
["mistook", "mistake"],
["mistaken", "mistake"],
["mistier", "misty"],
["misunderstood", "misunderstand"],
["modelling", "model"],
["modelled", "model"],
["modified", "modify"],
["moister", "moist"],
["mommas", "momma"],
["monkeys", "monkey"],
["monologues", "monologue"],
["moodier", "moody"],
["morgues", "morgue"],
["mortified", "mortify"],
["mosques", "mosque"],
["mosquitos", "mosquito"],
["mossier", "mossy"],
["mothers-in-law", "mother-in-law"],
["mottos", "motto"],
["mice", "mouse"],
["moustaches", "moustache"],
["movies", "movie"],
["mown", "mow"],
["messrs", "mr"],
["mse", "ms"],
["muddier", "muddy"],
["muddied", "muddy"],
["multiplied", "multiply"],
["murkier", "murky"],
["mustier", "musty"],
["mutinied", "mutiny"],
["mystified", "mystify"],
["narrower", "narrow"],
["nastier", "nasty"],
["naughtier", "naughty"],
["nearer", "near"],
["neater", "neat"],
["neckties", "necktie"],
["needier", "needy"],
["newer", "new"],
["newsmen", "newsman"],
["nicer", "nice"],
["niches", "niche"],
["niftier", "nifty"],
["nimbler", "nimble"],
["nos", "no"],
["nobler", "noble"],
["noisier", "noisy"],
["nominees", "nominee"],
["notified", "notify"],
["nuclei", "nucleus"],
["nullified", "nullify"],
["nuttier", "nutty"],
["oases", "oasis"],
["obeys", "obey"],
["obliques", "oblique"],
["obscurer", "obscure"],
["occupied", "occupy"],
["octopuses", "octopus"],
["odder", "odd"],
["odysseys", "odyssey"],
["offset", "offset"],
["oilier", "oily"],
["okays", "okay"],
["older", "old"],
["opuses", "opus"],
["opera", "opus"],
["orchestras", "orchestra"],
["outdid", "outdo"],
["outdone", "outdo"],
["outgrew", "outgrow"],
["outgrown", "outgrow"],
["outlays", "outlay"],
["outlaid", "outlay"],
["output", "output"],
["outran", "outrun"],
["overbore", "overbear"],
["overborne", "overbear"],
["overcame", "overcome"],
["overdid", "overdo"],
["overdone", "overdo"],
["overate", "overeat"],
["overeaten", "overeat"],
["overhung", "overhang"],
["overheard", "overhear"],
["overlies", "overlie"],
["overlay", "overlie"],
["overlain", "overlie"],
["overlying", "overlie"],
["overrode", "override"],
["overridden", "override"],
["overran", "overrun"],
["overrun", "overrun"],
["oversees", "oversee"],
["oversaw", "oversee"],
["overseen", "oversee"],
["overtook", "overtake"],
["overtaken", "overtake"],
["overthrew", "overthrow"],
["overthrown", "overthrow"],
["pacified", "pacify"],
["pakistanis", "pakistani"],
["palling", "pal"],
["palled", "pal"],
["paler", "pale"],
["panaceas", "panacea"],
["pancreases", "pancreas"],
["pandas", "panda"],
["panelling", "panel"],
["panelled", "panel"],
["panicking", "panic"],
["panicked", "panic"],
["panoramas", "panorama"],
["papas", "papa"],
["papayas", "papaya"],
["paras", "para"],
["parcelling", "parcel"],
["parcelled", "parcel"],
["parentheses", "parenthesis"],
["parkas", "parka"],
["parodied", "parody"],
["partook", "partake"],
["partaken", "partake"],
["passageways", "passageway"],
["pastas", "pasta"],
["pathways", "pathway"],
["patios", "patio"],
["patrolling", "patrol"],
["patrolled", "patrol"],
["patrolmen", "patrolman"],
["pays", "pay"],
["paid", "pay"],
["pc's", "pc"],
["peas", "pea"],
["pedalling", "pedal"],
["pedalled", "pedal"],
["pedigrees", "pedigree"],
["pees", "pee"],
["pelvises", "pelvis"],
["pent", "pen"],
["pencilling", "pencil"],
["pencilled", "pencil"],
["peninsulas", "peninsula"],
["penises", "penis"],
["perkier", "perky"],
["personas", "persona"],
["personae", "persona"],
["personified", "personify"],
["peskier", "pesky"],
["petrified", "petrify"],
["pettier", "petty"],
["phalanges", "phalanx"],
["phenomena", "phenomenon"],
["phobias", "phobia"],
["photos", "photo"],
["photocopied", "photocopy"],
["physiques", "physique"],
["pianos", "piano"],
["piazzas", "piazza"],
["pickier", "picky"],
["picnicking", "picnic"],
["picnicked", "picnic"],
["pies", "pie"],
["pinker", "pink"],
["pitied", "pity"],
["pizzas", "pizza"],
["placebos", "placebo"],
["plagues", "plague"],
["plainer", "plain"],
["plaques", "plaque"],
["plateaus", "plateau"],
["plateaux", "plateau"],
["plays", "play"],
["plazas", "plaza"],
["pleas", "plea"],
["pled", "plead"],
["pleasanter", "pleasant"],
["ploys", "ploy"],
["plumper", "plump"],
["pluses", "plus"],
["plusher", "plush"],
["plied", "ply"],
["policemen", "policeman"],
["politer", "polite"],
["polkas", "polka"],
["ponchos", "poncho"],
["poorer", "poor"],
["portfolios", "portfolio"],
["portrays", "portray"],
["posher", "posh"],
["posses", "posse"],
["prairies", "prairie"],
["prays", "pray"],
["preoccupied", "preoccupy"],
["prepays", "prepay"],
["prepaid", "prepay"],
["prettier", "pretty"],
["preys", "prey"],
["pricier", "pricey"],
["pros", "pro"],
["prognoses", "prognosis"],
["programming", "programme"],
["programmed", "programme"],
["prologues", "prologue"],
["propelling", "propel"],
["propelled", "propel"],
["prophesied", "prophesy"],
["prospectuses", "prospectus"],
["prouder", "proud"],
["proven", "prove"],
["pried", "pry"],
["psyches", "psyche"],
["psychos", "psycho"],
["psychoses", "psychosis"],
["puffing", "puff"],
["puffed", "puff"],
["puffier", "puffy"],
["pulleys", "pulley"],
["pummelling", "pummel"],
["pummelled", "pummel"],
["punier", "puny"],
["purer", "pure"],
["purees", "puree"],
["purified", "purify"],
["purring", "purr"],
["purred", "purr"],
["pursues", "pursue"],
["pushier", "pushy"],
["putting", "putt"],
["putted", "putt"],
["quainter", "quaint"],
["qualified", "qualify"],
["quantified", "quantify"],
["quanta", "quantum"],
["quarrelling", "quarrel"],
["quarrelled", "quarrel"],
["quarried", "quarry"],
["queasier", "queasy"],
["queerer", "queer"],
["queried", "query"],
["queues", "queue"],
["quicker", "quick"],
["quieter", "quiet"],
["quirkier", "quirky"],
["quizzes", "quiz"],
["quizzing", "quiz"],
["quizzed", "quiz"],
["quotas", "quota"],
["rabbis", "rabbi"],
["racier", "racy"],
["radios", "radio"],
["radii", "radius"],
["railways", "railway"],
["rainier", "rainy"],
["rallied", "rally"],
["rarer", "rare"],
["ratified", "ratify"],
["ratios", "ratio"],
["rays", "ray"],
["readied", "ready"],
["rebelling", "rebel"],
["rebelled", "rebel"],
["rebound", "rebind"],
["rebuffing", "rebuff"],
["rebuffed", "rebuff"],
["rebuilt", "rebuild"],
["rectified", "rectify"],
["redder", "red"],
["referees", "referee"],
["referenda", "referendum"],
["refuelling", "refuel"],
["refuelled", "refuel"],
["refugees", "refugee"],
["relays", "relay"],
["relaid", "relay"],
["relied", "rely"],
["remade", "remake"],
["remarried", "remarry"],
["remedied", "remedy"],
["remodelling", "remodel"],
["remodelled", "remodel"],
["remoter", "remote"],
["rent", "rend"],
["repays", "repay"],
["repaid", "repay"],
["repelling", "repel"],
["repelled", "repel"],
["replays", "replay"],
["replicas", "replica"],
["replied", "reply"],
["reran", "rerun"],
["rescues", "rescue"],
["resold", "resell"],
["residues", "residue"],
["retook", "retake"],
["retaken", "retake"],
["rethought", "rethink"],
["retinae", "retina"],
["retinas", "retina"],
["revving", "rev"],
["revved", "rev"],
["revelling", "revel"],
["revelled", "revel"],
["revenues", "revenue"],
["reveries", "reverie"],
["rewrote", "rewrite"],
["rewritten", "rewrite"],
["rhinos", "rhino"],
["richer", "rich"],
["rode", "ride"],
["ridden", "ride"],
["rang", "ring"],
["rung", "ring"],
["riper", "ripe"],
["rose", "rise"],
["risen", "rise"],
["riskier", "risky"],
["risottos", "risotto"],
["rivalling", "rival"],
["rivalled", "rival"],
["roadways", "roadway"],
["rockier", "rocky"],
["rodeos", "rodeo"],
["rogues", "rogue"],
["rookies", "rookie"],
["roomier", "roomy"],
["rosier", "rosy"],
["rougher", "rough"],
["rounder", "round"],
["rowdier", "rowdy"],
["ruddier", "ruddy"],
["ruder", "rude"],
["ran", "run"],
["runaways", "runaway"],
["runners-up", "runner-up"],
["runnier", "runny"],
["runways", "runway"],
["rustier", "rusty"],
["sadder", "sad"],
["safaris", "safari"],
["safer", "safe"],
["sagas", "saga"],
["salamis", "salami"],
["salesmen", "salesman"],
["salespeople", "salesperson"],
["saltier", "salty"],
["sandier", "sandy"],
["saner", "sane"],
["saris", "sari"],
["satisfied", "satisfy"],
["saudis", "saudi"],
["saunas", "sauna"],
["says", "say"],
["said", "say"],
["scanter", "scant"],
["scarcer", "scarce"],
["scarves", "scarf"],
["scarier", "scary"],
["scenarios", "scenario"],
["schemata", "schema"],
["schoolboys", "schoolboy"],
["schoolchildren", "schoolchild"],
["scoffing", "scoff"],
["scoffed", "scoff"],
["scrawnier", "scrawny"],
["screenplays", "screenplay"],
["scruffier", "scruffy"],
["scuffing", "scuff"],
["scuffed", "scuff"],
["scurried", "scurry"],
["seas", "sea"],
["seamen", "seaman"],
["sees", "see"],
["saw", "see"],
["seen", "see"],
["seedier", "seedy"],
["sought", "seek"],
["selves", "self"],
["sold", "sell"],
["sent", "send"],
["servicemen", "serviceman"],
["settees", "settee"],
["severer", "severe"],
["sewn", "sew"],
["sexier", "sexy"],
["shabbier", "shabby"],
["shadier", "shady"],
["shaggier", "shaggy"],
["shook", "shake"],
["shaken", "shake"],
["shakier", "shaky"],
["shallower", "shallow"],
["shampoos", "shampoo"],
["shapelier", "shapely"],
["sharper", "sharp"],
["shaven", "shave"],
["sheaves", "sheaf"],
["shorn", "shear"],
["shelves", "shelf"],
["shone", "shine"],
["shinier", "shiny"],
["shat", "shit"],
["shoddier", "shoddy"],
["shoes", "shoe"],
["shod", "shoe"],
["shodden", "shoe"],
["shot", "shoot"],
["shorter", "short"],
["shovelling", "shovel"],
["shovelled", "shovel"],
["shown", "show"],
["showier", "showy"],
["shrewder", "shrewd"],
["shriller", "shrill"],
["shrank", "shrink"],
["shrunk", "shrink"],
["shrunken", "shrink"],
["shrivelling", "shrivel"],
["shrivelled", "shrivel"],
["shyer", "shy"],
["shied", "shy"],
["sicker", "sick"],
["sicklier", "sickly"],
["signalling", "signal"],
["signalled", "signal"],
["signified", "signify"],
["silkier", "silky"],
["sillier", "silly"],
["silos", "silo"],
["simpler", "simple"],
["simplified", "simplify"],
["sang", "sing"],
["sung", "sing"],
["sank", "sink"],
["sunk", "sink"],
["sunken", "sink"],
["sinuses", "sinus"],
["sisters-in-law", "sister-in-law"],
["sat", "sit"],
["sketchier", "sketchy"],
["skis", "ski"],
[" skilled", "skill"],
["skimpier", "skimpy"],
["skinnier", "skinny"],
["slacker", "slack"],
["slays", "slay"],
["slew", "slay"],
["slain", "slay"],
["sleazier", "sleazy"],
["sleeker", "sleek"],
["slept", "sleep"],
["sleepier", "sleepy"],
["slicker", "slick"],
["slid", "slide"],
["slighter", "slight"],
["slimmer", "slim"],
["slimier", "slimy"],
["slung", "sling"],
["slunk", "slink"],
["sloppier", "sloppy"],
["slower", "slow"],
["slyer", "sly"],
["smaller", "small"],
["smarter", "smart"],
["smelt", "smell"],
["smellier", "smelly"],
["smote", "smite"],
["smitten", "smite"],
["smokier", "smoky"],
["smoother", "smooth"],
["smugger", "smug"],
["snappier", "snappy"],
["sneakier", "sneaky"],
["sniffing", "sniff"],
["sniffed", "sniff"],
["snorkelling", "snorkel"],
["snorkelled", "snorkel"],
["snowmen", "snowman"],
["snowshoes", "snowshoe"],
["snowier", "snowy"],
["snuffing", "snuff"],
["snuffed", "snuff"],
["snugger", "snug"],
["so-and-sos", "so-and-so"],
["soapier", "soapy"],
["soberer", "sober"],
["sodas", "soda"],
["sofas", "sofa"],
["softer", "soft"],
["soggier", "soggy"],
["solidified", "solidify"],
["solos", "solo"],
["somalis", "somali"],
["sons-in-law", "son-in-law"],
["sooner", "soon"],
["sopranos", "soprano"],
["sorrier", "sorry"],
["sorties", "sortie"],
["sounder", "sound"],
["sown", "sow"],
["spas", "spa"],
["sparser", "sparse"],
["spatulas", "spatula"],
["spoke", "speak"],
["spake", "speak"],
["spoken", "speak"],
["specified", "specify"],
["spectra", "spectrum"],
["sped", "speed"],
["speedier", "speedy"],
["spelt", "spell"],
["spent", "spend"],
["spicier", "spicy"],
["spikier", "spiky"],
["spilt", "spill"],
["spun", "spin"],
["spin-dried", "spin-dry"],
["spun", "spin-dry"],
["dry", "spin-dry"],
["spindlier", "spindly"],
["spiralling", "spiral"],
["spiralled", "spiral"],
["spat", "spit"],
["splays", "splay"],
["spoilt", "spoil"],
["spokesmen", "spokesman"],
["spokeswomen", "spokeswoman"],
["spongier", "spongy"],
["spookier", "spooky"],
["spoonsful", "spoonful"],
["sportsmen", "sportsman"],
["spottier", "spotty"],
["sprays", "spray"],
["sprees", "spree"],
["sprang", "spring"],
["sprung", "spring"],
["spied", "spy"],
["squeakier", "squeaky"],
["stadia", "stadium"],
["staffing", "staff"],
["staffed", "staff"],
["stairways", "stairway"],
["staler", "stale"],
["stood", "stand"],
["standbys", "standby"],
["stanzas", "stanza"],
["starker", "stark"],
["statelier", "stately"],
["statesmen", "statesman"],
["statues", "statue"],
["stauncher", "staunch"],
["stove", "stave"],
["stays", "stay"],
["staid", "stay"],
["steadier", "steady"],
["steadied", "steady"],
["stole", "steal"],
["stolen", "steal"],
["steamier", "steamy"],
["steeper", "steep"],
["stereos", "stereo"],
["sterner", "stern"],
["stuck", "stick"],
["stickier", "sticky"],
["stiffer", "stiff"],
["stigmas", "stigma"],
["stigmata", "stigma"],
["stilettos", "stiletto"],
["stiller", "still"],
["stimuli", "stimulus"],
["stung", "sting"],
["stingier", "stingy"],
["stank", "stink"],
["stunk", "stink"],
["stir-fried", "stir-fry"],
["stockier", "stocky"],
["stonier", "stony"],
["stormier", "stormy"],
["stouter", "stout"],
["straighter", "straight"],
["stranger", "strange"],
["strata", "stratum"],
["strays", "stray"],
["strewn", "strew"],
["stricter", "strict"],
["strode", "stride"],
["stridden", "stride"],
["strid", "stride"],
["struck", "strike"],
["stricken", "strike"],
["strung", "string"],
["stringier", "stringy"],
["strove", "strive"],
["striven", "strive"],
["stronger", "strong"],
["stubbier", "stubby"],
["studios", "studio"],
["studied", "study"],
["stuffing", "stuff"],
["stuffed", "stuff"],
["stuffier", "stuffy"],
["stupider", "stupid"],
["sturdier", "sturdy"],
["stymies", "stymie"],
["subcommittees", "subcommittee"],
["subdues", "subdue"],
["subpoenas", "subpoena"],
["subtler", "subtle"],
["subways", "subway"],
["sues", "sue"],
["sullied", "sully"],
["sunburnt", "sunburn"],
["sundaes", "sundae"],
["sunnier", "sunny"],
["supplied", "supply"],
["surer", "sure"],
["surlier", "surly"],
["surpluses", "surplus"],
["surveys", "survey"],
["swastikas", "swastika"],
["sways", "sway"],
["swore", "swear"],
["sworn", "swear"],
["swept", "sweep"],
["sweeter", "sweet"],
["swollen", "swell"],
["swifter", "swift"],
["swam", "swim"],
["swum", "swim"],
["swung", "swing"],
["swivelling", "swivel"],
["swivelled", "swivel"],
["syllabuses", "syllabus"],
["symposia", "symposium"],
["synagogues", "synagogue"],
["synopses", "synopsis"],
["syntheses", "synthesis"],
["tableaux", "tableau"],
["tableaus", "tableau"],
["taboos", "taboo"],
["tackier", "tacky"],
["took", "take"],
["taken", "take"],
["taller", "tall"],
["tallied", "tally"],
["tamer", "tame"],
["tangos", "tango"],
["tangier", "tangy"],
["tarter", "tart"],
["tastier", "tasty"],
["tattoos", "tattoo"],
["tauter", "taut"],
["tawnier", "tawny"],
["taxis", "taxi"],
["teas", "tea"],
["taught", "teach"],
["tore", "tear"],
["torn", "tear"],
["techniques", "technique"],
["tees", "tee"],
["told", "tell"],
["tempos", "tempo"],
["tenser", "tense"],
["terrified", "terrify"],
["terser", "terse"],
["testified", "testify"],
["thais", "thai"],
["those", "that"],
["thermoses", "thermos"],
["theses", "thesis"],
["thicker", "thick"],
["thieves", "thief"],
["thinner", "thin"],
["thought", "think"],
["thirstier", "thirsty"],
["these", "this"],
["thornier", "thorny"],
["threes", "three"],
["throve", "thrive"],
["thriven", "thrive"],
["threw", "throw"],
["thrown", "throw"],
["tidier", "tidy"],
["tidied", "tidy"],
["ties", "tie"],
["tying", "tie"],
["tighter", "tight"],
["tinier", "tiny"],
["tiptoes", "tiptoe"],
["tissues", "tissue"],
["toes", "toe"],
["tongues", "tongue"],
["teeth", "tooth"],
["tornados", "tornado"],
["torsos", "torso"],
["tortillas", "tortilla"],
["tost", "toss"],
["totalling", "total"],
["totalled", "total"],
["touchier", "touchy"],
["tougher", "tough"],
["towelling", "towel"],
["towelled", "towel"],
["toys", "toy"],
["trafficking", "traffic"],
["trafficked", "traffic"],
["trainees", "trainee"],
["traumas", "trauma"],
["travelling", "travel"],
["travelled", "travel"],
["trays", "tray"],
["trod", "tread"],
["trodden", "tread"],
["trees", "tree"],
["trekking", "trek"],
["trekked", "trek"],
["trendier", "trendy"],
["tribesmen", "tribesman"],
["trickier", "tricky"],
["trimmer", "trim"],
["trios", "trio"],
["trolleys", "trolley"],
["truer", "true"],
["trustees", "trustee"],
["trustier", "trusty"],
["tried", "try"],
["tundras", "tundra"],
["tunnelling", "tunnel"],
["tunnelled", "tunnel"],
["turves", "turf"],
["turkeys", "turkey"],
["tuxedos", "tuxedo"],
["twos", "two"],
["typified", "typify"],
["ufos", "ufo"],
["uglier", "ugly"],
["umbrellas", "umbrella"],
["uncannier", "uncanny"],
["underwent", "undergo"],
["undergone", "undergo"],
["underlies", "underlie"],
["underlying", "underlie"],
["underlay", "underlie"],
["underlain", "underlie"],
["understood", "understand"],
["undertook", "undertake"],
["undertaken", "undertake"],
["undervalues", "undervalue"],
["underwrote", "underwrite"],
["underwritten", "underwrite"],
["undid", "undo"],
["undone", "undo"],
["uneasier", "uneasy"],
["unfriendlier", "unfriendly"],
["unhappier", "unhappy"],
["unhealthier", "unhealthy"],
["unified", "unify"],
["unkinder", "unkind"],
["unravelling", "unravel"],
["unravelled", "unravel"],
["unties", "untie"],
["untying", "untie"],
["unwound", "unwind"],
["upheld", "uphold"],
["uteruses", "uterus"],
["utopias", "utopia"],
["vaginas", "vagina"],
["vaguer", "vague"],
["vainer", "vain"],
["valleys", "valley"],
["values", "value"],
["varied", "vary"],
["vaster", "vast"],
["vendettas", "vendetta"],
["venues", "venue"],
["verandas", "veranda"],
["verified", "verify"],
["vertebrae", "vertebra"],
["videos", "video"],
["vies", "vie"],
["vying", "vie"],
["viler", "vile"],
["vilified", "vilify"],
["villas", "villa"],
["virtues", "virtue"],
["virtuosos", "virtuoso"],
["virtuosi", "virtuoso"],
["viruses", "virus"],
["visas", "visa"],
["vistas", "vista"],
["vodkas", "vodka"],
["volleys", "volley"],
["vortices", "vortex"],
["wackier", "wacky"],
["woke", "wake"],
["woken", "wake"],
["walkie-talkies", "walkie-talkie"],
["walkways", "walkway"],
["warmer", "warm"],
["warier", "wary"],
["waterways", "waterway"],
["wavier", "wavy"],
["ways", "way"],
["weaker", "weak"],
["wealthier", "wealthy"],
["wore", "wear"],
["worn", "wear"],
["wearier", "weary"],
["wearied", "weary"],
["wove", "weave"],
["woven", "weave"],
["wees", "wee"],
["weekdays", "weekday"],
["wept", "weep"],
["weightier", "weighty"],
["weirder", "weird"],
["wharves", "wharf"],
["whiskeys", "whiskey"],
["whiter", "white"],
["whys", "why"],
["wider", "wide"],
["wives", "wife"],
["wilder", "wild"],
["'ll", "will"],
["ll", "will"],
["wilier", "wily"],
["won", "win"],
["wound", "wind"],
["windier", "windy"],
["wiser", "wise"],
["wist", "wit"],
["wot", "wit"],
["withdrew", "withdraw"],
["withdrawn", "withdraw"],
["withheld", "withhold"],
["withstood", "withstand"],
["wittier", "witty"],
["woes", "woe"],
["wolves", "wolf"],
["women", "woman"],
["woos", "woo"],
["woodier", "woody"],
["woollier", "woolly"],
["wrought", "work"],
["workdays", "workday"],
["workmen", "workman"],
["worried", "worry"],
["worthier", "worthy"],
["wrapt", "wrap"],
["wrung", "wring"],
["wrote", "write"],
["written", "write"],
["x-rays", "x-ray"],
["yellower", "yellow"],
["yeses", "yes"],
["yo-yos", "yo-yo"],
["younger", "young"],
["yourselves", "yourself"],
["yuppies", "yuppie"],
["zebras", "zebra"],
["zeros", "zero"],
["zombies", "zombie"],
["zoos", "zoo"],
["zul", "zulu"],
["blest", "bless"],
["bluest", "blue"],
["cruellest", "cruel"],
["eeriest", "eerie"],
["farthest", "far"],
["freest", "free"],
["gooiest", "gooey"],
["oddest", "odd"],
["priciest", "pricey"],
["stiffest", "stiff"],
["truest", "true"],
["vaguest", "vague"],
["barest", "bare"],
["cutest", "cute"],
["finest", "fine"],
["hugest", "huge"],
["palest", "pale"],
["ripest", "ripe"],
["severest", "severe"],
]);

var lemExs2 = new Set([
"lens", // s
"ms",
"ps",
"summons",
"airbed", // ed
"airspeed",
"bed",
"biped",
"bleed",
"bobsled",
"bottle-feed",
"breast-feed",
"breed",
"clear-headed",
"coloured",
"cowshed",
"creed",
"crossbreed",
"deathbed",
"deed",
"ed",
"embed",
"exceed",
"feed",
"flowerbed",
"force-feed",
"good-humoured",
"heed",
"hotbed",
"hundred",
"misdeed",
"moped",
"need",
"nosebleed",
"overfeed",
"pay-bed",
"proceed",
"quadruped",
"red",
"reed",
"seaweed",
"seed",
"seedbed",
"semi-detached",
"shed",
"shred",
"sickbed",
"sled",
"sofa-bed",
"speed",
"spoon-feed",
"steed",
"succeed",
"ted",
"thoroughbred",
"tweed",
"waterbed",
"watershed",
"wed",
"weed",
"woodshed",
"thing", // ing
"something",
"anything",
"everything",
"during",
"bring",
"nothing",
"morning",
"spring",
"evening",
"sing",
"ring",
"wing",
"king",
"swing",
"ceiling",
"string",
"ongoing",
"sibling",
"cling",
"fling",
"viking",
"darling",
"offspring",
"pending",
"earring",
"outing",
"sting",
"impending",
"pudding",
"sling",
"herring",
"wring",
"hamstring",
"casing",
"sterling",
"awning",
"inkling",
"scathing",
"sapling",
"hulking",
"best", // est
"interest",
"suggest",
"test",
"west",
"rest",
"forest",
"guest",
"chest",
"invest",
"request",
"arrest",
"priest",
"honest",
"protest",
"contest",
"modest",
"quest",
"nest",
"harvest",
"manifest",
"vest",
"pest",
"earnest",
"crest",
"conquest",
"attest",
"lest",
"unrest",
"digest",
"eldest",
"molest",
"zest",
"self-interest",
"rainforest",
"incest",
"second-largest",
"dishonest",
"ingest",
"subtest",
"wrest",
"t-test",
"detest",
"east-west",
"test-retest",
"behest",
"infest",
"third-largest",
"bequest",
"divest",
]);